"""Simulate plausible Arduino Uno serial output for the two item-4(a)/4(c) sketches.

No physical Arduino Uno was available to flash and capture real serial
output for arduino_uno_a_busy_loop/ and arduino_uno_c_interrupt/. This
script produces a *labeled simulation* instead of fabricating a fake
hardware capture: it models each mechanism's timing behavior from first
principles (loop-blocking vs. hardware-timer-driven sampling) on the
ATmega328P, and injects small, realistic imperfections (timer jitter, one
merged interrupt sample under backlog) so the output pattern looks like
what a real capture would produce, rather than an idealized clean log.
Every generated file is stamped "SIMULATED" and this script is the only
source of that data. The ESP32-WROOM sketches already have real captures
in firmware/real_logs/ and are NOT touched by this script.

Model assumptions (documented, not hidden):
  - ATmega328P at 16 MHz. A `volatile unsigned long long` (64-bit)
    add-and-store in the summation loop is far more expensive on this 8-bit
    core than on the ESP32's 32-bit Xtensa: each 64-bit add decomposes into
    a chain of 8-bit adds-with-carry plus loop overhead, estimated here at
    ~800,000 additions/second (vs. ~20,000,000/s assumed for the ESP32
    model previously used in this project).
  - Timer1 CTC-mode ISR period: OCR1A=1562 at a 16 MHz / 1024 prescaler
    gives (1562+1)/15625 s = 100.032 ms, so the nominal period used here is
    100.03 ms rather than exactly 100 ms.
  - Timer1 ISR jitter: uniform +-1 ms (comparable hardware-timer precision
    to the ESP32 model).
"""

from __future__ import annotations

import os
import random

random.seed(7)  # reproducible "small errors", different seed from the ESP32 script

NOMINAL_PERIOD_MS = 100.03  # Timer1 CTC period, see module docstring
SUM_RATE_PER_SEC = 800_000  # additions/second on the ATmega328P, see module docstring
SUM_LIMITS = [1_000_000, 10_000_000, 100_000_000]
N_SAMPLES_TO_SHOW = 8

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "simulated_logs_arduino_uno")

HEADER = (
    "# SIMULATED serial output -- no physical Arduino Uno was flashed for this run.\n"
    "# Generated by firmware/simulate_arduino_uno_serial_output.py from a timing model, not a hardware capture.\n"
    "# The ESP32-WROOM sketches have real captures in firmware/real_logs/ instead.\n"
    "# See firmware/README.md for the model assumptions.\n"
)


def sum_time_ms(n: int) -> float:
    return (n / SUM_RATE_PER_SEC) * 1000.0


def simulate_busy_loop(n: int) -> list[str]:
    """4(a): sampling and summation share one thread -> period = 100.03ms + T_sum."""
    lines = []
    t_sum = sum_time_ms(n)
    for _ in range(N_SAMPLES_TO_SHOW):
        dt = NOMINAL_PERIOD_MS + t_sum + random.uniform(-1.0, 1.0)
        pot1, pot2, pot3 = (random.randint(0, 1023) for _ in range(3))  # 10-bit ADC
        lines.append(f"dt_ms={dt:.1f} pot1={pot1} pot2={pot2} pot3={pot3}")
    return lines


def simulate_interrupt(n: int) -> list[str]:
    """4(c): Timer1 ISR keeps exact timing; loop() can lag behind it under a large N."""
    lines = []
    t_sum = sum_time_ms(n)
    backlog_periods = max(1, round(t_sum / NOMINAL_PERIOD_MS)) if t_sum > NOMINAL_PERIOD_MS else 1

    for i in range(N_SAMPLES_TO_SHOW):
        if t_sum > NOMINAL_PERIOD_MS and i == 3:
            dt = NOMINAL_PERIOD_MS * backlog_periods + random.uniform(-2.0, 2.0)
            pot1, pot2, pot3 = (random.randint(0, 1023) for _ in range(3))
            lines.append(
                f"[isr] dt_ms={dt:.1f} pot1={pot1} pot2={pot2} pot3={pot3}  "
                f"# NOTE: loop() lagged {backlog_periods} periods behind the ISR"
            )
        else:
            dt = NOMINAL_PERIOD_MS + random.uniform(-1.0, 1.0)
            pot1, pot2, pot3 = (random.randint(0, 1023) for _ in range(3))
            lines.append(f"[isr] dt_ms={dt:.1f} pot1={pot1} pot2={pot2} pot3={pot3}")
    return lines


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    simulators = {
        "arduino_a_busy_loop": simulate_busy_loop,
        "arduino_c_interrupt": simulate_interrupt,
    }

    for label, sim_fn in simulators.items():
        for n in SUM_LIMITS:
            lines = sim_fn(n)
            filename = f"{label}_N{n}.txt"
            with open(os.path.join(OUT_DIR, filename), "w") as f:
                f.write(HEADER)
                f.write(f"# mechanism={label} SUM_LIMIT={n}\n\n")
                f.write("\n".join(lines) + "\n")

            dts = [float(l.split("dt_ms=")[1].split(" ")[0]) for l in lines]
            avg_dt = sum(dts) / len(dts)
            print(f"{label:>22} N={n:>11,}  avg dt_ms={avg_dt:10.1f}  -> {filename}")


if __name__ == "__main__":
    main()
