"""Simulate plausible ESP32-WROOM serial output for the three item-4 sketches.

No physical ESP32/Arduino Uno was available to flash and capture real serial
output for this assignment. This script produces a *labeled simulation*
instead of fabricating a fake hardware capture: it models each mechanism's
timing behavior from first principles (loop-blocking vs. task-yielding vs.
hardware-timer-driven sampling) and injects small, realistic imperfections
(scheduling jitter, one merged interrupt sample) so the output pattern looks
like what a real capture would produce, rather than an idealized clean log.
Every generated file is stamped "SIMULATED" and this script is the only
source of that data — nothing here is asserted as a real measurement.

Model assumptions (documented, not hidden):
  - ESP32 Xtensa core clocked at 240 MHz; a `volatile unsigned long long`
    add-and-store in the summation loop costs ~12 cycles once compiler
    optimizations are limited by `volatile` -> ~20e6 additions/second.
  - FreeRTOS `vTaskDelay` scheduling jitter: uniform +-2 ms.
  - Hardware timer ISR jitter: uniform +-0 to 1 ms (near-exact hardware
    clock reference).
"""

from __future__ import annotations

import os
import random

random.seed(42)  # reproducible "small errors"

SAMPLE_PERIOD_MS = 100
SUM_RATES_PER_SEC = 20_000_000  # additions/second, see module docstring
SUM_LIMITS = [10_000_000, 1_000_000, 100_000_000]
N_SAMPLES_TO_SHOW = 8

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "simulated_logs")

HEADER = (
    "# SIMULATED serial output -- no physical ESP32-WROOM was flashed for this run.\n"
    "# Generated by firmware/simulate_serial_output.py from a timing model, not a hardware capture.\n"
    "# See firmware/README.md for the model assumptions.\n"
)


def sum_time_ms(n: int) -> float:
    return (n / SUM_RATES_PER_SEC) * 1000.0


def simulate_busy_loop(n: int) -> list[str]:
    """4(a): sampling and summation share one thread -> period = 100ms + T_sum."""
    lines = []
    t_sum = sum_time_ms(n)
    for i in range(N_SAMPLES_TO_SHOW):
        dt = SAMPLE_PERIOD_MS + t_sum + random.uniform(-0.5, 0.5)
        pot1, pot2, pot3 = (random.randint(0, 4095) for _ in range(3))
        lines.append(f"dt_ms={dt:.1f} pot1={pot1} pot2={pot2} pot3={pot3}")
    return lines


def simulate_dualcore(n: int) -> list[str]:
    """4(b): sampling task on core 0, summation on core 1 -> ~100ms +- jitter."""
    lines = []
    for i in range(N_SAMPLES_TO_SHOW):
        dt = SAMPLE_PERIOD_MS + random.uniform(-2.0, 2.0)
        pot1, pot2, pot3 = (random.randint(0, 4095) for _ in range(3))
        lines.append(f"[core0] dt_ms={dt:.1f} pot1={pot1} pot2={pot2} pot3={pot3}")
    return lines


def simulate_interrupt(n: int) -> list[str]:
    """4(c): hardware timer ISR keeps exact timing; loop() can lag behind it.

    Injects one small, realistic error: when T_sum exceeds one sample period,
    loop() cannot drain samples as fast as the ISR produces them, so one
    "processed late" merged sample is shown with an inflated dt_ms (the
    accumulated backlog since the last time loop() caught up) instead of
    silently pretending every sample is printed on schedule.
    """
    lines = []
    t_sum = sum_time_ms(n)
    backlog_periods = max(1, round(t_sum / SAMPLE_PERIOD_MS)) if t_sum > SAMPLE_PERIOD_MS else 1

    for i in range(N_SAMPLES_TO_SHOW):
        if t_sum > SAMPLE_PERIOD_MS and i == 3:
            # One realistic hiccup: loop() falls behind, then catches up with
            # a merged sample carrying the accumulated backlog's dt.
            dt = SAMPLE_PERIOD_MS * backlog_periods + random.uniform(-1.0, 1.0)
            pot1, pot2, pot3 = (random.randint(0, 4095) for _ in range(3))
            lines.append(
                f"[isr] dt_ms={dt:.1f} pot1={pot1} pot2={pot2} pot3={pot3}  "
                f"# NOTE: loop() lagged {backlog_periods} periods behind the ISR"
            )
        else:
            dt = SAMPLE_PERIOD_MS + random.uniform(-1.0, 1.0)
            pot1, pot2, pot3 = (random.randint(0, 4095) for _ in range(3))
            lines.append(f"[isr] dt_ms={dt:.1f} pot1={pot1} pot2={pot2} pot3={pot3}")
    return lines


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    simulators = {
        "a_busy_loop": simulate_busy_loop,
        "b_dualcore": simulate_dualcore,
        "c_interrupt": simulate_interrupt,
    }

    summary_rows = []
    for label, sim_fn in simulators.items():
        for n in SUM_LIMITS:
            lines = sim_fn(n)
            filename = f"{label}_N{n}.txt"
            with open(os.path.join(OUT_DIR, filename), "w") as f:
                f.write(HEADER)
                f.write(f"# mechanism={label} SUM_LIMIT={n}\n\n")
                f.write("\n".join(lines) + "\n")

            dts = [float(l.split("dt_ms=")[1].split(" ")[0]) for l in lines]
            avg_dt = sum(dts) / len(dts)
            summary_rows.append((label, n, avg_dt))
            print(f"{label:>12} N={n:>11,}  avg dt_ms={avg_dt:8.1f}  -> {filename}")

    return summary_rows


if __name__ == "__main__":
    main()
